#%RAML 1.0 DataType
type: object
properties:
  emp_name:
    type: string
    example: "A"
  emp_status:
    type: string
    example: "A"
  emp_exp:
    type: string
    example: "A"
  emp_dob:
    type: date-only
    example: "2022-09-01"
  emp_ctc:
    type: string
    example: "A"
  emp_technology:
    type: string
    example: "A"
  emp_address:
    type: string
    example: "A"
  emp_unit:
    type: string
    example: "A"