#%RAML 1.0 SecurityScheme
type: x-clientEnforcement
describedBy:
  headers:
    clientId:
      type: string
      required: true
      example: "aaa"
    clientSecret:
      type: string
      required: true
      example: "aaa"